struct ques{
    char q[300]; // For storing question
    char op_1[30]; //For storing options 
    char op_2[30];
    char op_3[30];
    char op_4[30];
    char op_corr[30]; // For storing correct option , to be used in 50-50 lifeline.
    int corr; // Correct option number is stored.
};
struct ques id[18]={"Who wrote Ramayana?","Valmiki","Kabir","Lord ganesh","Tanmay Bhat","Valmiki",1,"When did 9/11 attack occur?","9/11","2/11","10/11","11/11","9/11",1,"Which of the following is a browser ?","Google Chrome","Google","Internet","Whatsapp","Google Chrome",1,"The language of Lakshadweep,a Union Territory of India, is","Tamil","Hindi","Malayalam","Telugu","Malayalam",3,"Bahubali festival is related to","Islam","Hinduism","Jainism","Buddhism","Jainism",3,"Which day is observed as the World Standards  Day?","June 26","Oct 14","Nov 15","Dec 2","Oct 14",2,"September 27 is celebrated every year as","Teachers Day","World Tourism Day","Childrens Day","Republic Day","World Tourism Day",2,"Who is the author of Manas Ka-Hans ?","Amrit Lal Nagar","PremChand","Jayshankar Prasad","Khuswant Singh","Amrit Lal Nagar",1,"Who is the author of the epic Meghdoot ?","Kalidas","Valmiki","BanaBHatta","Vishakadatta","Kalidas",1,"Which of the following is observed as Sports Day every year?","22 April","26 July","29 August","2 October","29 August",3,"World Health Day is observed on : ","April 7","March 6","March 15","April 28","April 7",1,"Pongal is a popular festival of which state?","Karnataka","Kerela","Tamil Nadu","Andhra Pradesh","Tamil Nadu",3,"Which of the following Muslim festivals is based on the Holy Quran ?","Id-ul-Zuha","Id-ul-Fitr","Bakri-Id","MOharram","Id-ul-Zuha",1,"Van Mahotsav was started by","Maharshi Karve","Bal Gangadhar Tilak","K.M.Munshi","Sanjay Gandhi","K.M.Munshi",3,"The first month of the Indian national calendar is","Magha","Chaitra","Ashadha","Vaishaka","Chaitra",2,"Which of the following is not a dance from Kerala?","Yaksha Gana","Kathakali","Mohiniattam","Ottan Thullai","Yaksha Gana",1,"The Lalit Kala Academy is devoted to the promotion of","Dance And Drama","Fine Arts","Literature","Music","Fine Arts",2,"Which one of the following is essentially a solo dance? ","Mohiniattam","Manipuri","Kathak","Kuchipudi","Mohiniattam",1};
